### ISSUE TITLE
Add support for multiple remotes

### ISSUE THREAD

**Issue by tomi2108** [trevorhauter/gitportal.nvim#64]
Users can have multiple remotes for one repository. We could add support for specifying the remote name (origin by default). Maybe as a parameter to each command so users can have keybindings for each remote? 

Don't know if this is a frequent use case tbh. What do you think? @trevorhauter

Something like:
 
```lua

return {
  'trevorhauter/gitportal.nvim',
  config = function()
    local gitportal = require("gitportal")

    gitportal.setup({
      always_include_current_line = true,
      default_remote = "not_origin" -- if not set "origin" is taken as default
    })

    vim.keymap.set("n", "<leader>gp", function() gitportal.open_file_in_browser({ remote = "another_remote" }) end) -- takes precedence over default_remote
    vim.keymap.set("v", '<leader>gc', function() gitportal.copy_link_to_clipboard() end) -- if not set default_remote is used
  end
}


```

**Comment by trevorhauter** [comment]
Oh wow, I didn't know one could have multiple remotes. How does that manifest in the `.git` file?

I think this is something we should definitely add support for! In the short term tho I'd like to wait until the test coverage improves around these methods (something I'm working on now). Tho I could be swayed if others deemed it helpful in the short term and we did extensive testing on another branch

**Comment by tomi2108** [comment]
You get another entry in your `.git/config` file.

```toml
[remote "origin"]
	url = https://gitlab-ee.agil.movistar.com.ar/mimovistarempresas/frontend/app-shell.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	glab-resolved = base
	glab-resolved = head
[remote "tomi"]
	url = http://github.com/tomi
	fetch = +refs/heads/*:refs/remotes/tomi/*
```
